name: Build Package

on:
  workflow_dispatch:
    inputs:
      tmate_enabled:
        type: boolean
        description: 'With TMATE'
        required: false
        default: false

  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make SPEC
        shell: bash
        run: |
          #se a pasta SPECS não existir, criar
          if [ ! -d "rpmbuild/SPECS/" ];then
            mkdir -p rpmbuild/SPECS/
          fi
          bash package.rpmbuild
          
      - name: Make Source
        shell: bash
        run: |
          #make source.tar.gz
          name=$(cat rpmbuild/SPECS/rpmbuild.spec | grep Name: | cut -d ":" -f2 | sed 's/^ \+//')
          version=$(cat rpmbuild/SPECS/rpmbuild.spec | grep Version: | cut -d ":" -f2 | sed 's/^ \+//')

          #se a pasta SOURCES não existir, criar
          if [ ! -d "rpmbuild/SOURCES/" ];then
            mkdir -p rpmbuild/SOURCES/
          fi

          #renomear pasta
          mv source ${name}-${version}

          #compactar source para empacotamento
          tar -cvzf rpmbuild/SOURCES/source.tar.gz ${name}-${version}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.tmate_enabled }}
      
      - name: Update github
        shell: bash
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add rpmbuild
          git commit -m "new RPM Package and Source $(date +%y-%m-%d_%H:%M)"
          git push
      
      - name: Send Hooks BigLinux Build Package
        shell: bash
        run: |
          event=$(echo ${{ github.repository }} | sed 's/biglinux/biglinux-RPM/')
          echo $event
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/BigLinux-Package-Build/build-package/dispatches \
            -d '{"event_type":"$event","client_payload":{"unit":false,"integration":true}}
